#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! OpenAPI definition
//! Source: /work/openapi/openapi.yaml
//! Version: v0
//! Generated by `oas3-gen v0.25.3`
//!

use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;
pub const BASE_URL: &str = "http://app:8080";
#[derive(Debug, Clone)]
pub struct OpenApiDefinitionClient {
    pub client: Client,
    pub base_url: Url,
}
impl Default for OpenApiDefinitionClient {
    fn default() -> Self {
        Self::new()
    }
}
impl OpenApiDefinitionClient {
    /// Create a client using the OpenAPI `servers[0]` URL.
    #[must_use]
    #[track_caller]
    pub fn new() -> Self {
        Self {
            client: Client::builder().build().expect("client"),
            base_url: Url::parse(BASE_URL).expect("valid base url"),
        }
    }
    /// Create a client with a custom base URL.
    pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
        Ok(Self {
            client: Client::builder().build().context("building reqwest client")?,
            base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
        })
    }
    /// Create a client from an existing `reqwest::Client`.
    pub fn with_client(
        base_url: impl AsRef<str>,
        client: Client,
    ) -> anyhow::Result<Self> {
        let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
        Ok(Self { client, base_url: url })
    }
    /// * Path: `GET /api/v1/files`
    pub async fn get_files(
        &self,
        request: GetFilesRequest,
    ) -> anyhow::Result<GetFilesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("api")
            .push("v1")
            .push("files");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetFilesRequest::parse_response(response).await?)
    }
    /// * Path: `POST /api/v1/files/upload`
    pub async fn upload(
        &self,
        request: UploadRequest,
    ) -> anyhow::Result<UploadResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("api")
            .push("v1")
            .push("files")
            .push("upload");
        let response = self
            .client
            .post(url)
            .query(&request.query)
            .json(&request.body)
            .send()
            .await?;
        Ok(UploadRequest::parse_response(response).await?)
    }
    /// * Path: `GET /api/v1/files/{id}`
    pub async fn download_file(
        &self,
        request: DownloadFileRequest,
    ) -> anyhow::Result<DownloadFileResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("api")
            .push("v1")
            .push("files")
            .push(&request.path.id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(DownloadFileRequest::parse_response(response).await?)
    }
    /// * Path: `GET /api/v1/folders`
    pub async fn get_folders(
        &self,
        request: GetFoldersRequest,
    ) -> anyhow::Result<GetFoldersResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("api")
            .push("v1")
            .push("folders");
        let response = self.client.get(url).send().await?;
        Ok(GetFoldersRequest::parse_response(response).await?)
    }
    /// * Path: `POST /api/v1/folders`
    pub async fn create_folder_1(
        &self,
        request: CreateFolder1Request,
    ) -> anyhow::Result<GetFoldersResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("api")
            .push("v1")
            .push("folders");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(CreateFolder1Request::parse_response(response).await?)
    }
    /// * Path: `POST /api/v1/folders/{parentFolderId}`
    pub async fn create_folder(
        &self,
        request: CreateFolderRequest,
    ) -> anyhow::Result<GetFoldersResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("api")
            .push("v1")
            .push("folders")
            .push(&request.path.parent_folder_id.to_string());
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(CreateFolderRequest::parse_response(response).await?)
    }
    /// * Path: `GET /api/v1/version`
    pub async fn get_version(
        &self,
        request: GetVersionRequest,
    ) -> anyhow::Result<GetVersionResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("api")
            .push("v1")
            .push("version");
        let response = self.client.get(url).send().await?;
        Ok(GetVersionRequest::parse_response(response).await?)
    }
}

