#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! OpenAPI definition
//! Source: /work/openapi/openapi.yaml
//! Version: v0
//! Generated by `oas3-gen v0.25.3`
//!

use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct CreateFolder1Request {
    pub body: CreateFolderView,
}
impl CreateFolder1Request {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetFoldersResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                Folder200Response,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetFoldersResponse::Ok(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetFoldersResponse::Unknown);
    }
}
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct CreateFolderRequest {
    pub path: CreateFolderRequestPath,
    pub body: CreateFolderView,
}
impl CreateFolderRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetFoldersResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                Folder200Response,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetFoldersResponse::Ok(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetFoldersResponse::Unknown);
    }
}
#[derive(Debug, Clone, PartialEq, oas3_gen_support::Default)]
pub struct CreateFolderRequestPath {
    pub parent_folder_id: uuid::Uuid,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub struct CreateFolderView {
    pub name: Option<String>,
}
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct DownloadFileRequest {
    pub path: DownloadFileRequestPath,
}
impl DownloadFileRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<DownloadFileResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                StreamingResponseBody,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(DownloadFileResponse::Ok(data));
        }
        let _ = req.bytes().await?;
        return Ok(DownloadFileResponse::Unknown);
    }
}
#[derive(Debug, Clone, PartialEq, oas3_gen_support::Default)]
pub struct DownloadFileRequestPath {
    pub id: uuid::Uuid,
}
/// Response types for downloadFile
#[derive(Debug, Clone)]
pub enum DownloadFileResponse {
    ///200: OK
    Ok(StreamingResponseBody),
    ///default: Unknown response
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct FileInfoView {
    #[serde(rename = "folderId")]
    pub folder_id: Option<uuid::Uuid>,
    pub id: Option<uuid::Uuid>,
    pub name: Option<String>,
    #[serde(rename = "sizeBytes")]
    pub size_bytes: Option<i64>,
}
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub struct FileRequestBody {
    pub file: Vec<u8>,
}
pub type Folder200Response = Vec<FolderView>;
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct FolderView {
    pub id: Option<uuid::Uuid>,
    pub name: Option<String>,
    #[serde(rename = "nestedFolders")]
    pub nested_folders: Option<Vec<FolderView>>,
}
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetFilesRequest {
    pub query: GetFilesRequestQuery,
}
impl GetFilesRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetFilesResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                PageFileInfoView,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetFilesResponse::Ok(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetFilesResponse::Unknown);
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub struct GetFilesRequestQuery {
    pub pageable: serde_json::Value,
}
/// Response types for getFiles
#[derive(Debug, Clone)]
pub enum GetFilesResponse {
    ///200: OK
    Ok(PageFileInfoView),
    ///default: Unknown response
    Unknown,
}
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetFoldersRequest {}
impl GetFoldersRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetFoldersResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                Folder200Response,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetFoldersResponse::Ok(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetFoldersResponse::Unknown);
    }
}
/// Response types for getFolders
#[derive(Debug, Clone)]
pub enum GetFoldersResponse {
    ///200: OK
    Ok(Folder200Response),
    ///default: Unknown response
    Unknown,
}
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetVersionRequest {}
impl GetVersionRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetVersionResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                VersionView,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetVersionResponse::Ok(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetVersionResponse::Unknown);
    }
}
/// Response types for getVersion
#[derive(Debug, Clone)]
pub enum GetVersionResponse {
    ///200: OK
    Ok(VersionView),
    ///default: Unknown response
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct PageFileInfoView {
    pub content: Option<Vec<FileInfoView>>,
    pub empty: Option<bool>,
    pub first: Option<bool>,
    pub last: Option<bool>,
    pub number: Option<i32>,
    #[serde(rename = "numberOfElements")]
    pub number_of_elements: Option<i32>,
    pub pageable: Option<PageableObject>,
    pub size: Option<i32>,
    pub sort: Option<SortObject>,
    #[serde(rename = "totalElements")]
    pub total_elements: Option<i64>,
    #[serde(rename = "totalPages")]
    pub total_pages: Option<i32>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    Deserialize,
    validator::Validate,
    oas3_gen_support::Default
)]
pub struct Pageable {
    #[validate(range(min = 0i32))]
    pub page: Option<i32>,
    #[validate(range(min = 1i32))]
    pub size: Option<i32>,
    pub sort: Option<Vec<String>>,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct PageableObject {
    pub offset: Option<i64>,
    #[serde(rename = "pageNumber")]
    pub page_number: Option<i32>,
    #[serde(rename = "pageSize")]
    pub page_size: Option<i32>,
    pub paged: Option<bool>,
    pub sort: Option<SortObject>,
    pub unpaged: Option<bool>,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct SortObject {
    pub empty: Option<bool>,
    pub sorted: Option<bool>,
    pub unsorted: Option<bool>,
}
pub type StreamingResponseBody = serde_json::Value;
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct UploadRequest {
    pub query: UploadRequestQuery,
    pub body: FileRequestBody,
}
impl UploadRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<UploadResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                FileInfoView,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(UploadResponse::Ok(data));
        }
        let _ = req.bytes().await?;
        return Ok(UploadResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub struct UploadRequestQuery {
    #[serde(rename = "folderId")]
    pub folder_id: Option<uuid::Uuid>,
}
/// Response types for upload
#[derive(Debug, Clone)]
pub enum UploadResponse {
    ///200: OK
    Ok(FileInfoView),
    ///default: Unknown response
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct VersionView {
    pub name: Option<String>,
    pub version: Option<String>,
}

