openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://app:8080
  description: Generated server url
paths:
  /api/v1/folders/{parentFolderId}:
    post:
      tags:
      - folders-controller
      operationId: createFolder
      parameters:
      - name: parentFolderId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFolderView"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FolderView"
  /api/v1/folders:
    get:
      tags:
      - folders-controller
      operationId: getFolders
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FolderView"
    post:
      tags:
      - folders-controller
      operationId: createFolder_1
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFolderView"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FolderView"
  /api/v1/files/upload:
    post:
      tags:
      - files-controller
      operationId: upload
      parameters:
      - name: folderId
        in: query
        required: false
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FileInfoView"
  /api/v1/version:
    get:
      tags:
      - version-controller
      operationId: getVersion
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/VersionView"
  /api/v1/files:
    get:
      tags:
      - files-controller
      operationId: getFiles
      parameters:
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageFileInfoView"
  /api/v1/files/{id}:
    get:
      tags:
      - files-controller
      operationId: downloadFile
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StreamingResponseBody"
components:
  schemas:
    CreateFolderView:
      type: object
      properties:
        name:
          type: string
    FolderView:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        nestedFolders:
          type: array
          items:
            $ref: "#/components/schemas/FolderView"
    FileInfoView:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        folderId:
          type: string
          format: uuid
        sizeBytes:
          type: integer
          format: int64
    VersionView:
      type: object
      properties:
        version:
          type: string
        name:
          type: string
    Pageable:
      type: object
      properties:
        page:
          type: integer
          format: int32
          minimum: 0
        size:
          type: integer
          format: int32
          minimum: 1
        sort:
          type: array
          items:
            type: string
    PageFileInfoView:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/FileInfoView"
        number:
          type: integer
          format: int32
        pageable:
          $ref: "#/components/schemas/PageableObject"
        sort:
          $ref: "#/components/schemas/SortObject"
        numberOfElements:
          type: integer
          format: int32
        first:
          type: boolean
        last:
          type: boolean
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        paged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        unpaged:
          type: boolean
    SortObject:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
    StreamingResponseBody: {}
